import { images } from './images';

export const coffees = [
  {
    id: '001',
    name: 'Expresso Tradicional',
    coffeeImage: images.ExpressoTradicional,
    description: 'O tradicional café feito com água quente e grãos moídos',
    tags: ['TRADICIONAL'],
    price: 9.9,
  },
  {
    id: '002',
    name: 'Expresso Americano',
    coffeeImage: images.ExpressoAmericano,
    description: 'Expresso diluído, menos intenso que o tradicional',
    tags: ['TRADICIONAL'],
    price: 9.9,
  },
  {
    id: '003',
    name: 'Expresso Cremoso',
    coffeeImage: images.ExpressoCremoso,
    description: 'Café expresso tradicional com espuma cremosa',
    tags: ['TRADICIONAL'],
    price: 9.9,
  },
  {
    id: '004',
    name: 'Expresso Gelado',
    coffeeImage: images.ExpressoGelado,
    description: 'Bebida preparada com café expresso e cubos de gelo',
    tags: ['TRADICIONAL', 'GELADO'],
    price: 9.9,
  },
  {
    id: '005',
    name: 'Café com Leito',
    coffeeImage: images.CafeComLeite,
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    tags: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
  },
  {
    id: '006',
    name: 'Latte',
    coffeeImage: images.Latte,
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    tags: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
  },
  {
    id: '007',
    name: 'Capuccino',
    coffeeImage: images.Capuccino,
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    tags: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
  },
  {
    id: '008',
    name: 'Macchiato',
    coffeeImage: images.Macchiato,
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    tags: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
  },
  {
    id: '009',
    name: 'Mocaccino',
    coffeeImage: images.Mochaccino,
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    tags: ['TRADICIONAL', ''],
    price: 9.9,
  },
  {
    id: '010',
    name: 'Chocolate Quente',
    coffeeImage: images.ChocolateQuente,
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    tags: ['ESPECIAL', 'COM LEITE'],
    price: 9.9,
  },
  {
    id: '011',
    name: 'Cubano',
    coffeeImage: images.Cubano,
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    tags: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    price: 9.9,
  },
  {
    id: '012',
    name: 'Havaiano',
    coffeeImage: images.Havaiano,
    description: 'Bebida adocicada preparada com café e leite de coco',
    tags: ['ESPECIAL'],
    price: 9.9,
  },
  {
    id: '013',
    name: 'Árabe',
    coffeeImage: images.Arabe,
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    tags: ['ESPECIAL'],
    price: 9.9,
  },
  {
    id: '014',
    name: 'Irlandês',
    coffeeImage: images.Irlandes,
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    tags: ['ESPECIAL', 'ALCOÓLICO'],
    price: 9.9,
  },
];
